// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClickableTrController from "./clickable_tr_controller.js"
application.register("clickable-tr", ClickableTrController)

import FilterController from "./filter_controller.js"
application.register("filter", FilterController)
